//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAPT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAPRequestDetail
    {
        public int Id { get; set; }
        public int BAPTMasterId { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string VendorResponse { get; set; }
        public string BAPTResponse { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual BAPTMaster BAPTMaster { get; set; }
    }
}
