//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAPT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAPTXOPricing
    {
        public int Id { get; set; }
        public string LoopType { get; set; }
        public string IPType { get; set; }
        public Nullable<int> DownLoad { get; set; }
        public Nullable<int> Upload { get; set; }
        public Nullable<decimal> MRC { get; set; }
        public Nullable<decimal> NRC { get; set; }
        public Nullable<int> Term { get; set; }
        public string PriceGroup { get; set; }
        public string Network { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<decimal> Install { get; set; }
    }
}
