//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAPT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAPTMaster
    {
        public BAPTMaster()
        {
            this.BAPRequestDetails = new HashSet<BAPRequestDetail>();
        }
    
        public int Id { get; set; }
        public string RequeslInput { get; set; }
        public Nullable<int> RequestCount { get; set; }
        public string RequestFrom { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateRequestSent { get; set; }
        public string Status { get; set; }
        public string VendorQuote { get; set; }
        public string Exception { get; set; }
    
        public virtual ICollection<BAPRequestDetail> BAPRequestDetails { get; set; }
    }
}
