//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAPT.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BAPTEntities : DbContext
    {
        public BAPTEntities()
            : base("name=BAPTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAPTMaster> BAPTMasters { get; set; }
        public virtual DbSet<ResponseDetail> ResponseDetails { get; set; }
        public virtual DbSet<BAPTXOPricing> BAPTXOPricings { get; set; }
        public virtual DbSet<BAPRequestDetail> BAPRequestDetails { get; set; }
        public virtual DbSet<BAPTRequestReady> BAPTRequestReadies { get; set; }
        public virtual DbSet<BAPTXOPricingHistory> BAPTXOPricingHistories { get; set; }
        public virtual DbSet<Markup> Markups { get; set; }
    }
}
