//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAPT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseDetail
    {
        public int Id { get; set; }
        public string VendorQuote { get; set; }
        public string BroadbandType { get; set; }
        public string PriceGroup { get; set; }
        public string Prequal { get; set; }
        public string LocationName { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string BTN { get; set; }
        public string Ilec { get; set; }
        public string CableProvider { get; set; }
        public string MultiIPATT { get; set; }
        public string MessageComcast { get; set; }
        public string RecommendationsCharter { get; set; }
        public string ReasonCharter { get; set; }
        public string ServiceabilityTWC { get; set; }
        public string MessageWOW { get; set; }
        public string NewWaveAvailability { get; set; }
        public string MegaPathAvailability { get; set; }
        public string LoopType { get; set; }
        public string iptype { get; set; }
        public string Download { get; set; }
        public string Upload { get; set; }
        public string MRC { get; set; }
        public string NRC { get; set; }
        public string professionalinstall { get; set; }
        public string Term { get; set; }
        public string Customer_Reference { get; set; }
        public Nullable<System.DateTime> DateReceieved { get; set; }
        public string XOMRC { get; set; }
        public string XONRC { get; set; }
        public string Network { get; set; }
    }
}
